import React, { useMemo, useState } from 'react';
import {
  Search,
  Tags,
  ArrowLeftRight,
  Wrench,
  ClipboardList,
  MapPin,
  Layers,
  Users,
  Package,
  ArrowRight,
  Images,
  X,
  ChevronLeft,
  ChevronRight,
  QrCode as QrCodeIcon,
  ScanLine,
  History,
  CheckCircle2,
  Plus,
  Filter,
  Download,
  TrendingUp,
  RotateCcw,
  Route,
  Boxes,
  CalendarClock,
  SendHorizontal,
  AlertTriangle,
  AlertOctagon,
  ClipboardCheck,
  Wallet,
  RefreshCw,
  PlusCircle,
  Trash2,
  Clock,
} from 'lucide-react';
import type { SparePart, ActivityLog, SiteLocation } from '../../types';
import { getCategoryVisual } from '../../data/categoryVisuals';
import { QRCodeModal } from './QRCodeModal';
import { BarcodeScannerModal } from './BarcodeScannerModal';
import { TransferModal } from './TransferModal';
import type { AdminView } from './Sidebar';

export const SETU_GALLERY: { src: string; caption: string }[] = [
  { src: '/assets/images/setu/setu-01.webp', caption: 'Sambungan & Fitting Perpipaan Gas' },
  { src: '/assets/images/setu/setu-02.webp', caption: 'Jalur Distribusi Pipa Compressor Station' },
  { src: '/assets/images/setu/setu-03.webp', caption: 'Unit Meter Turbin Gas' },
  { src: '/assets/images/setu/setu-04.webp', caption: 'Panel Kontrol Elektrikal Site' },
  { src: '/assets/images/setu/setu-05.webp', caption: 'Regulator & Valve Tekanan Tinggi' },
  { src: '/assets/images/setu/setu-06.webp', caption: 'Rangkaian Skid Instrumentasi' },
  { src: '/assets/images/setu/setu-07.webp', caption: 'Plat Spesifikasi Peralatan' },
  { src: '/assets/images/setu/setu-08.webp', caption: 'Area Skid Compressor Terbungkus' },
  { src: '/assets/images/setu/setu-09.webp', caption: 'Gardu & Jaringan Listrik Site' },
  { src: '/assets/images/setu/setu-10.webp', caption: 'Panel Distribusi Daya Site Setu' },
  { src: '/assets/images/setu/setu-11.webp', caption: 'APAR & Perlengkapan Keselamatan' },
  { src: '/assets/images/setu/setu-12.webp', caption: 'Instalasi Skid & Rak Peralatan' },
  { src: '/assets/images/setu/setu-13.webp', caption: 'Unit AC Ruang Fleet' },
  { src: '/assets/images/setu/setu-14.webp', caption: 'Unit AC Ruang Fleet (Tampak Lain)' },
  { src: '/assets/images/setu/setu-15.webp', caption: 'Label Barcode Aset Terdaftar' },
  { src: '/assets/images/setu/setu-16.webp', caption: 'Label Barcode Aset pada Furnitur Site' },
];

export const SITE_LABEL: Record<SiteLocation, string> = {
  bekasi: 'Bekasi',
  indramayu: 'Indramayu',
  blora: 'Blora',
  setu: 'Setu',
};

const SITE_SUB: Record<SiteLocation, string> = {
  bekasi: 'Mother Station & Workshop',
  indramayu: 'Daughter Station & Depot',
  blora: 'Wellhead & Processing Plant',
  setu: 'Compressor Station & Fleet Room',
};

const SITE_IMAGE: Record<SiteLocation, string> = {
  bekasi: '/assets/images/cng-cylinder.webp',
  indramayu: '/assets/images/distribution-truck.webp',
  blora: '/assets/images/cng-pipe.webp',
  setu: '/assets/images/setu/setu-02.webp',
};

const SITE_COLOR: Record<SiteLocation, string> = {
  bekasi: '#00D084',
  indramayu: '#60A5FA',
  blora: '#FBBF24',
  setu: '#C084FC',
};

function formatIDR(val: number): string {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(val);
}

function PageHeader({ icon: Icon, title, sub }: { icon: React.ElementType; title: string; sub: string }) {
  return (
    <div className="view-page-header">
      <div className="view-page-title">
        <Icon size={22} color="#00D084" />
        {title}
      </div>
      <div className="view-page-sub">{sub}</div>
    </div>
  );
}

// QR codes generated by the app encode full URLs, e.g.
// "https://inventory.reethau.id/asset/{sku}" or ".../site/{siteId}".
// A raw barcode/SKU label, on the other hand, is just the plain code.
// This extracts the actual searchable term so a scanned/typed/pasted value
// behaves the same as typing the SKU / site name manually — used both for
// the camera scanner and for hardware "keyboard-wedge" barcode scanners
// (which type straight into the focused search field) or manual paste.
function parseScanCode(raw: string): { term: string; site?: SiteLocation } {
  const trimmed = raw.trim();
  try {
    const url = new URL(trimmed);
    const parts = url.pathname.split('/').filter(Boolean); // e.g. ['site','bekasi'] or ['asset','SKU-1']
    if (parts.length >= 2 && parts[0] === 'site') {
      const siteId = parts[1].toLowerCase() as SiteLocation;
      if (siteId in SITE_LABEL) {
        return { term: SITE_LABEL[siteId], site: siteId };
      }
      return { term: decodeURIComponent(parts[1]) };
    }
    if (parts.length >= 2 && parts[0] === 'asset') {
      return { term: decodeURIComponent(parts[1]) };
    }
    if (parts.length > 0) {
      return { term: decodeURIComponent(parts[parts.length - 1]) };
    }
    return { term: trimmed };
  } catch {
    // Not a URL — treat the scanned value as a plain SKU/barcode.
    return { term: trimmed };
  }
}

/* ────────────────────────────── Global Search ────────────────────────────── */
export const GlobalSearchView: React.FC<{
  spareParts: SparePart[];
  logs: ActivityLog[];
  onNavigate?: (view: AdminView) => void;
}> = ({ spareParts, logs, onNavigate }) => {
  const [q, setQ] = useState('');
  const [isScannerOpen, setIsScannerOpen] = useState(false);
  const [scanNotice, setScanNotice] = useState<{ code: string; matched: boolean } | null>(null);
  const query = q.trim().toLowerCase();

  const partResults = query
    ? spareParts.filter(
        (p) =>
          p.name.toLowerCase().includes(query) ||
          p.sku.toLowerCase().includes(query) ||
          p.specifications.toLowerCase().includes(query) ||
          p.category.toLowerCase().includes(query) ||
          p.productEnergy.toLowerCase().includes(query) ||
          SITE_LABEL[p.site].toLowerCase().includes(query)
      )
    : [];

  const logResults = query
    ? logs.filter((l) => l.description.toLowerCase().includes(query) || l.performedBy.toLowerCase().includes(query))
    : [];

  const topCategories = useMemo(() => {
    const counts = new Map<string, number>();
    spareParts.forEach((p) => counts.set(p.category, (counts.get(p.category) ?? 0) + 1));
    return Array.from(counts.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, 6)
      .map(([name]) => name);
  }, [spareParts]);

  const resolveScanMatch = (term: string, site?: SiteLocation): boolean =>
    site
      ? spareParts.some((p) => p.site === site)
      : spareParts.some(
          (p) => p.sku.toLowerCase() === term.toLowerCase() || p.sku.toLowerCase().includes(term.toLowerCase())
        );

  const handleScanResult = (code: string) => {
    const { term, site } = parseScanCode(code);
    setQ(term);
    setIsScannerOpen(false);
    setScanNotice({ code, matched: resolveScanMatch(term, site) });
  };

  return (
    <div>
      <PageHeader icon={Search} title="Global Search" sub="Cari spare part, SKU, spesifikasi, atau riwayat aktivitas di seluruh site" />

      <div className="glass-panel" style={{ borderRadius: '16px', padding: '1rem 1.25rem', marginBottom: query || scanNotice ? '1rem' : '1.5rem' }}>
        <div className="gsearch-input-row">
          <div style={{ position: 'relative', flex: 1, minWidth: 0 }}>
            <Search size={18} color="#64748B" style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)' }} />
            <input
              autoFocus
              type="text"
              value={q}
              onChange={(e) => {
                const raw = e.target.value;
                // Hardware/keyboard-wedge barcode scanners "type" the scanned
                // value straight into whichever field is focused, and users
                // may also paste a scanned URL directly — handle those the
                // same way as the in-app camera scanner.
                if (/^https?:\/\//i.test(raw.trim())) {
                  const { term, site } = parseScanCode(raw);
                  setQ(term);
                  setScanNotice({ code: raw.trim(), matched: resolveScanMatch(term, site) });
                } else {
                  setQ(raw);
                  setScanNotice(null);
                }
              }}
              placeholder="Ketik, atau scan barcode / QR spare part..."
              style={{
                width: '100%',
                background: 'rgba(10, 15, 29, 0.8)',
                border: '1px solid rgba(255,255,255,0.1)',
                borderRadius: '10px',
                padding: '0.85rem 1rem 0.85rem 2.75rem',
                color: 'var(--txt-primary)',
                fontSize: '0.95rem',
                outline: 'none',
              }}
            />
          </div>
          <button
            type="button"
            className="gsearch-scan-btn"
            onClick={() => {
              setScanNotice(null);
              setIsScannerOpen(true);
            }}
          >
            <ScanLine size={18} />
            Scan
          </button>
        </div>
      </div>

      {scanNotice && (
        <div className="gsearch-scan-toast" style={!scanNotice.matched ? { background: 'rgba(245, 158, 11, 0.1)', borderColor: 'rgba(245, 158, 11, 0.35)', color: '#F59E0B' } : undefined}>
          <CheckCircle2 size={16} />
          {scanNotice.matched
            ? `Kode "${scanNotice.code}" terdeteksi dan cocok dengan katalog.`
            : `Kode "${scanNotice.code}" terdeteksi, namun tidak ditemukan di katalog.`}
        </div>
      )}

      {query && (
        <>
          <div style={{ fontSize: '0.8rem', color: 'var(--txt-muted)', fontWeight: 700, marginBottom: '0.75rem', textTransform: 'uppercase' }}>
            Spare Part ({partResults.length})
          </div>
          <div className="glass-panel simple-table-wrap" style={{ borderRadius: '16px', marginBottom: '1.5rem' }}>
            <table className="simple-table">
              <tbody>
                {partResults.length === 0 && (
                  <tr><td className="cell-empty" style={{ color: 'var(--txt-muted)' }}>Tidak ada spare part yang cocok.</td></tr>
                )}
                {partResults.map((p) => (
                  <tr key={p.id}>
                    <td className="cell-lead" style={{ color: 'var(--txt-primary)', fontWeight: 600 }}>
                      {p.name}
                      <div style={{ fontFamily: 'monospace', color: '#00D084', fontSize: '0.72rem', fontWeight: 700, marginTop: '0.2rem' }}>{p.sku}</div>
                    </td>
                    <td data-label="Site">Site {SITE_LABEL[p.site]}</td>
                    <td data-label="Stok">{p.stock} {p.unit}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div style={{ fontSize: '0.8rem', color: 'var(--txt-muted)', fontWeight: 700, marginBottom: '0.75rem', textTransform: 'uppercase' }}>
            Riwayat Aktivitas ({logResults.length})
          </div>
          <div className="glass-panel simple-table-wrap" style={{ borderRadius: '16px' }}>
            <table className="simple-table">
              <tbody>
                {logResults.length === 0 && (
                  <tr><td className="cell-empty" style={{ color: 'var(--txt-muted)' }}>Tidak ada aktivitas yang cocok.</td></tr>
                )}
                {logResults.map((l) => (
                  <tr key={l.id}>
                    <td className="cell-lead" style={{ color: 'var(--txt-primary)' }}>
                      {l.description}
                      <div style={{ color: 'var(--txt-muted)', fontSize: '0.72rem', marginTop: '0.2rem' }}>{l.timestamp}</div>
                    </td>
                    <td data-label="Oleh" style={{ color: 'var(--txt-tertiary)' }}>{l.performedBy}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      {!query && (
        <div className="gsearch-empty">
          <div className="gsearch-empty-hero">
            <div className="gsearch-empty-hero-icon">
              <Search size={28} />
            </div>
            <div style={{ color: 'var(--txt-primary)', fontWeight: 700, fontSize: '1rem', marginBottom: '0.35rem' }}>
              Mulai ketik atau scan barcode
            </div>
            <div style={{ color: 'var(--txt-muted)', fontSize: '0.85rem', maxWidth: '420px', margin: '0 auto' }}>
              Cari spare part berdasarkan nama, SKU, kategori, atau spesifikasi — atau langsung scan label barcode/QR di lapangan untuk pencarian instan.
            </div>
          </div>

          <div className="gsearch-action-grid">
            <button type="button" className="gsearch-action-card" onClick={() => setIsScannerOpen(true)}>
              <div className="gsearch-action-card-icon" style={{ background: 'rgba(0, 208, 132, 0.15)', color: '#00D084' }}>
                <ScanLine size={20} />
              </div>
              <div className="gsearch-action-card-title">Scan Barcode / QR</div>
              <div className="gsearch-action-card-sub">Gunakan kamera untuk memindai label SKU spare part secara instan.</div>
            </button>

            <button
              type="button"
              className="gsearch-action-card"
              onClick={() => onNavigate?.('categories')}
              disabled={!onNavigate}
              style={!onNavigate ? { cursor: 'default', opacity: 0.6 } : undefined}
            >
              <div className="gsearch-action-card-icon" style={{ background: 'rgba(56, 189, 248, 0.15)', color: '#38BDF8' }}>
                <Tags size={20} />
              </div>
              <div className="gsearch-action-card-title">Jelajahi Kategori</div>
              <div className="gsearch-action-card-sub">Lihat ringkasan stok per kategori spare part di seluruh site.</div>
            </button>

            <button
              type="button"
              className="gsearch-action-card"
              onClick={() => onNavigate?.('audit')}
              disabled={!onNavigate}
              style={!onNavigate ? { cursor: 'default', opacity: 0.6 } : undefined}
            >
              <div className="gsearch-action-card-icon" style={{ background: 'rgba(244, 114, 182, 0.15)', color: '#F472B6' }}>
                <History size={20} />
              </div>
              <div className="gsearch-action-card-title">Riwayat Aktivitas</div>
              <div className="gsearch-action-card-sub">Telusuri log transfer, penambahan, dan perubahan stok terbaru.</div>
            </button>
          </div>

          {topCategories.length > 0 && (
            <div className="gsearch-chip-section">
              <div className="gsearch-chip-label">Pencarian Cepat &mdash; Kategori</div>
              <div className="gsearch-chips">
                {topCategories.map((cat) => {
                  const visual = getCategoryVisual(cat);
                  const Icon = visual.icon;
                  return (
                    <button key={cat} type="button" className="gsearch-chip" onClick={() => setQ(cat)}>
                      <Icon size={13} color={visual.color} />
                      {cat}
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          <div className="gsearch-chip-section">
            <div className="gsearch-chip-label">Pencarian Cepat &mdash; Site</div>
            <div className="gsearch-chips">
              {(Object.keys(SITE_LABEL) as SiteLocation[]).map((site) => (
                <button key={site} type="button" className="gsearch-chip" onClick={() => setQ(SITE_LABEL[site])}>
                  <MapPin size={13} />
                  Site {SITE_LABEL[site]}
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      <BarcodeScannerModal isOpen={isScannerOpen} onClose={() => setIsScannerOpen(false)} onScan={handleScanResult} />
    </div>
  );
};

/* ────────────────────────────── Categories ────────────────────────────── */
export const CategoriesView: React.FC<{ spareParts: SparePart[] }> = ({ spareParts }) => {
  const grouped = Object.entries(
    spareParts.reduce<Record<string, { count: number; stock: number; value: number }>>((acc, p) => {
      if (!acc[p.category]) acc[p.category] = { count: 0, stock: 0, value: 0 };
      acc[p.category].count += 1;
      acc[p.category].stock += p.stock;
      acc[p.category].value += p.stock * p.priceEstimate;
      return acc;
    }, {})
  );

  return (
    <div>
      <PageHeader icon={Tags} title="Kategori Spare Part" sub="Ringkasan tiap kategori produk di seluruh site" />
      <div className="kpi-grid">
        {grouped.map(([name, data]) => {
          const visual = getCategoryVisual(name);
          const Icon = visual.icon || Package;
          return (
            <div key={name} className="glass-panel" style={{ borderRadius: '16px', padding: '1.25rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
                <div
                  style={{
                    width: '40px',
                    height: '40px',
                    borderRadius: '10px',
                    background: visual?.bg || 'rgba(255,255,255,0.06)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                >
                  <Icon size={20} color={visual?.color || 'var(--txt-tertiary)'} />
                </div>
                <div style={{ fontWeight: 700, color: 'var(--txt-primary)', fontSize: '0.9rem' }}>{name}</div>
              </div>
              <div style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--txt-primary)' }}>
                {data.stock} <span style={{ fontSize: '0.8rem', color: 'var(--txt-muted)', fontWeight: 500 }}>unit / {data.count} jenis</span>
              </div>
              <div style={{ fontSize: '0.78rem', color: '#00D084', marginTop: '0.4rem' }}>{formatIDR(data.value)}</div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

/* ────────────────────────────── Assignments (Transfers) ────────────────────────────── */
const emptyInputStyle: React.CSSProperties = {
  background: 'var(--bg-root)',
  border: '1px solid var(--border-subtle)',
  borderRadius: '10px',
  padding: '0.65rem 0.85rem',
  color: 'var(--txt-primary)',
  fontSize: '0.85rem',
  outline: 'none',
};

function initialsOf(name: string): string {
  const clean = name.split('(')[0].trim();
  const parts = clean.split(' ').filter(Boolean);
  if (parts.length === 0) return '?';
  return (parts[0][0] + (parts[1]?.[0] ?? '')).toUpperCase();
}

/** Small popup letting the user pick which spare part to move, before the
 * existing TransferModal (target site + quantity) takes over. */
const PartPickerModal: React.FC<{
  isOpen: boolean;
  spareParts: SparePart[];
  onClose: () => void;
  onPick: (item: SparePart) => void;
}> = ({ isOpen, spareParts, onClose, onPick }) => {
  const [q, setQ] = useState('');
  if (!isOpen) return null;

  const query = q.trim().toLowerCase();
  const results = spareParts
    .filter((p) => p.stock > 0)
    .filter(
      (p) =>
        !query ||
        p.name.toLowerCase().includes(query) ||
        p.sku.toLowerCase().includes(query) ||
        SITE_LABEL[p.site].toLowerCase().includes(query)
    )
    .slice(0, 40);

  return (
    <div
      className="admin-modal-overlay"
      style={{ zIndex: 110 }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="glass-panel admin-modal-panel" style={{ maxWidth: '520px', border: '1px solid rgba(0, 208, 132, 0.4)' }}>
        <button
          onClick={onClose}
          style={{
            position: 'absolute', top: '1.25rem', right: '1.25rem',
            background: 'rgba(255, 255, 255, 0.05)', border: 'none', color: 'var(--txt-tertiary)',
            borderRadius: '50%', width: '32px', height: '32px', cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}
        >
          <X size={18} />
        </button>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.25rem', paddingRight: '2.75rem' }}>
          <div style={{ width: '44px', height: '44px', borderRadius: '12px', background: 'rgba(0, 208, 132, 0.15)', color: '#00D084', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
            <SendHorizontal size={22} />
          </div>
          <div style={{ minWidth: 0 }}>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: 'var(--txt-primary)' }}>Transfer Baru</h3>
            <div style={{ fontSize: '0.8rem', color: 'var(--txt-muted)' }}>Pilih spare part yang ingin dipindahkan</div>
          </div>
        </div>

        <div style={{ position: 'relative', marginBottom: '1rem' }}>
          <Search size={16} color="#64748B" style={{ position: 'absolute', left: '0.85rem', top: '50%', transform: 'translateY(-50%)' }} />
          <input
            autoFocus
            type="text"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Cari nama, SKU, atau site asal..."
            style={{ ...emptyInputStyle, width: '100%', padding: '0.7rem 0.85rem 0.7rem 2.5rem' }}
          />
        </div>

        <div style={{ maxHeight: '360px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          {results.length === 0 && (
            <div style={{ color: 'var(--txt-muted)', fontSize: '0.85rem', textAlign: 'center', padding: '1.5rem 0' }}>
              Tidak ada spare part dengan stok tersedia yang cocok.
            </div>
          )}
          {results.map((p) => (
            <button
              key={p.id}
              type="button"
              onClick={() => onPick(p)}
              style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem',
                background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)',
                borderRadius: '10px', padding: '0.65rem 0.85rem', cursor: 'pointer', textAlign: 'left',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'rgba(0, 208, 132, 0.4)'; e.currentTarget.style.background = 'rgba(0, 208, 132, 0.06)'; }}
              onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'rgba(255,255,255,0.07)'; e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; }}
            >
              <div style={{ minWidth: 0 }}>
                <div style={{ fontSize: '0.75rem', color: '#00D084', fontFamily: 'monospace', fontWeight: 700 }}>{p.sku}</div>
                <div style={{ fontSize: '0.9rem', color: 'var(--txt-primary)', fontWeight: 600, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{p.name}</div>
                <div style={{ fontSize: '0.75rem', color: 'var(--txt-muted)', marginTop: '0.15rem' }}>
                  Site {SITE_LABEL[p.site]} &middot; {p.stock} {p.unit} tersedia
                </div>
              </div>
              <ArrowRight size={16} color="#64748B" style={{ flexShrink: 0 }} />
            </button>
          ))}
        </div>
      </div>
    </div>
  );
};

export const AssignmentsView: React.FC<{
  spareParts: SparePart[];
  logs: ActivityLog[];
  onConfirmTransfer: (item: SparePart, quantity: number, targetSite: SiteLocation) => void;
}> = ({ spareParts, logs, onConfirmTransfer }) => {
  const [isPickerOpen, setIsPickerOpen] = useState(false);
  const [transferItem, setTransferItem] = useState<SparePart | null>(null);
  const [search, setSearch] = useState('');
  const [fromFilter, setFromFilter] = useState<SiteLocation | 'all'>('all');
  const [toFilter, setToFilter] = useState<SiteLocation | 'all'>('all');
  const [sortOrder, setSortOrder] = useState<'newest' | 'oldest'>('newest');

  const allTransfers = useMemo(
    () => logs.filter((l): l is ActivityLog & { siteFrom: SiteLocation; siteTo: SiteLocation } =>
      l.action === 'TRANSFER' && !!l.siteFrom && !!l.siteTo
    ),
    [logs]
  );

  const filtersActive = search.trim() !== '' || fromFilter !== 'all' || toFilter !== 'all';

  const transfers = useMemo(() => {
    const q = search.trim().toLowerCase();
    let list = allTransfers.filter((l) => {
      if (fromFilter !== 'all' && l.siteFrom !== fromFilter) return false;
      if (toFilter !== 'all' && l.siteTo !== toFilter) return false;
      if (q && !l.description.toLowerCase().includes(q) && !l.performedBy.toLowerCase().includes(q)) return false;
      return true;
    });
    list = [...list].sort((a, b) =>
      sortOrder === 'newest' ? b.timestamp.localeCompare(a.timestamp) : a.timestamp.localeCompare(b.timestamp)
    );
    return list;
  }, [allTransfers, search, fromFilter, toFilter, sortOrder]);

  // Extract "N unit" from the auto-generated description so we can total it
  // without needing a dedicated numeric field on ActivityLog.
  const totalUnits = useMemo(
    () => allTransfers.reduce((sum, l) => {
      const match = l.description.match(/Transfer\s+(\d+)/i);
      return sum + (match ? parseInt(match[1], 10) : 0);
    }, 0),
    [allTransfers]
  );

  const thisMonthCount = useMemo(() => {
    const now = new Date();
    return allTransfers.filter((l) => {
      const d = new Date(l.timestamp.replace(' ', 'T'));
      return !Number.isNaN(d.getTime()) && d.getFullYear() === now.getFullYear() && d.getMonth() === now.getMonth();
    }).length;
  }, [allTransfers]);

  const topRoute = useMemo(() => {
    const counts = new Map<string, { from: SiteLocation; to: SiteLocation; count: number }>();
    allTransfers.forEach((l) => {
      const key = `${l.siteFrom}->${l.siteTo}`;
      const existing = counts.get(key);
      if (existing) existing.count += 1;
      else counts.set(key, { from: l.siteFrom, to: l.siteTo, count: 1 });
    });
    return Array.from(counts.values()).sort((a, b) => b.count - a.count)[0] ?? null;
  }, [allTransfers]);

  const resetFilters = () => {
    setSearch('');
    setFromFilter('all');
    setToFilter('all');
  };

  const handleExportCsv = () => {
    const header = ['Waktu', 'Deskripsi', 'Dari', 'Ke', 'Oleh'];
    const rows = transfers.map((l) => [
      l.timestamp,
      l.description.replace(/"/g, "'"),
      SITE_LABEL[l.siteFrom],
      SITE_LABEL[l.siteTo],
      l.performedBy.replace(/"/g, "'"),
    ]);
    const csv = [header, ...rows].map((r) => r.map((cell) => `"${cell}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `reethau-transfer-antar-site-${new Date().toISOString().slice(0, 10)}.csv`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const statCards = [
    { label: 'Total Transfer', value: allTransfers.length.toLocaleString('id-ID'), icon: ArrowLeftRight, color: '#00D084' },
    { label: 'Total Unit Dipindahkan', value: totalUnits.toLocaleString('id-ID'), icon: Boxes, color: '#60A5FA' },
    { label: 'Transfer Bulan Ini', value: thisMonthCount.toLocaleString('id-ID'), icon: CalendarClock, color: '#FBBF24' },
    {
      label: 'Rute Teraktif',
      value: topRoute ? `${SITE_LABEL[topRoute.from]} → ${SITE_LABEL[topRoute.to]}` : '—',
      sub: topRoute ? `${topRoute.count}x transfer` : 'Belum ada data',
      icon: Route,
      color: '#C084FC',
    },
  ];

  const siteOptions: SiteLocation[] = ['bekasi', 'indramayu', 'blora', 'setu'];

  return (
    <div>
      <div className="view-toolbar-row" style={{ display: 'flex', flexWrap: 'wrap', gap: '1rem', justifyContent: 'space-between', alignItems: 'flex-end' }}>
        <PageHeader icon={ArrowLeftRight} title="Transfer Antar Site" sub="Riwayat perpindahan spare part antar lokasi operasional" />
        <button type="button" className="btn-primary view-toolbar-btn" onClick={() => setIsPickerOpen(true)} style={{ marginBottom: '1.5rem' }}>
          <Plus size={18} />
          Transfer Baru
        </button>
      </div>

      {/* Summary cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem', marginBottom: '1.5rem' }}>
        {statCards.map((s) => (
          <div key={s.label} className="glass-panel" style={{ borderRadius: '16px', padding: '1.25rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
              <div style={{ width: '38px', height: '38px', borderRadius: '10px', background: `${s.color}26`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <s.icon size={18} color={s.color} />
              </div>
              <div style={{ fontSize: '0.78rem', color: 'var(--txt-tertiary)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.02em' }}>{s.label}</div>
            </div>
            <div style={{ fontSize: '1.35rem', fontWeight: 800, color: 'var(--txt-primary)', lineHeight: 1.2 }}>{s.value}</div>
            {s.sub && <div style={{ fontSize: '0.78rem', color: s.color, marginTop: '0.25rem', fontWeight: 600 }}>{s.sub}</div>}
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="glass-panel" style={{ borderRadius: '16px', padding: '1rem 1.25rem', marginBottom: '1.5rem', display: 'flex', flexWrap: 'wrap', gap: '0.75rem', alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--txt-muted)', fontSize: '0.8rem', fontWeight: 700 }}>
          <Filter size={15} />
          Filter
        </div>
        <div style={{ position: 'relative', flex: '1 1 220px', minWidth: '180px' }}>
          <Search size={15} color="#64748B" style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)' }} />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Cari deskripsi atau nama petugas..."
            style={{ ...emptyInputStyle, width: '100%', padding: '0.65rem 0.85rem 0.65rem 2.25rem' }}
          />
        </div>
        <select value={fromFilter} onChange={(e) => setFromFilter(e.target.value as SiteLocation | 'all')} style={{ ...emptyInputStyle, cursor: 'pointer', flex: '1 1 150px' }}>
          <option value="all">Semua Site Asal</option>
          {siteOptions.map((s) => <option key={s} value={s}>Dari {SITE_LABEL[s]}</option>)}
        </select>
        <select value={toFilter} onChange={(e) => setToFilter(e.target.value as SiteLocation | 'all')} style={{ ...emptyInputStyle, cursor: 'pointer', flex: '1 1 150px' }}>
          <option value="all">Semua Site Tujuan</option>
          {siteOptions.map((s) => <option key={s} value={s}>Ke {SITE_LABEL[s]}</option>)}
        </select>
        <select value={sortOrder} onChange={(e) => setSortOrder(e.target.value as 'newest' | 'oldest')} style={{ ...emptyInputStyle, cursor: 'pointer', flex: '1 1 150px' }}>
          <option value="newest">Terbaru dahulu</option>
          <option value="oldest">Terlama dahulu</option>
        </select>
        {filtersActive && (
          <button type="button" className="btn-chip" onClick={resetFilters} style={{ flex: '0 1 auto' }}>
            <RotateCcw size={14} />
            Reset
          </button>
        )}
        <button type="button" className="btn-chip" onClick={handleExportCsv} disabled={transfers.length === 0} style={transfers.length === 0 ? { opacity: 0.5, cursor: 'not-allowed', flex: '1 1 auto', justifyContent: 'center' } : { flex: '1 1 auto', justifyContent: 'center' }}>
          <Download size={14} />
          Ekspor CSV
        </button>
      </div>

      <div style={{ fontSize: '0.8rem', color: 'var(--txt-muted)', fontWeight: 700, marginBottom: '0.75rem', textTransform: 'uppercase', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
        <TrendingUp size={14} color="#00D084" />
        Riwayat Transfer ({transfers.length})
      </div>

      <div className="glass-panel simple-table-wrap" style={{ borderRadius: '16px', padding: '0.5rem' }}>
        <table className="simple-table">
          <thead>
            <tr>
              <th>Waktu</th>
              <th>Deskripsi</th>
              <th>Rute</th>
              <th>Oleh</th>
            </tr>
          </thead>
          <tbody>
            {transfers.length === 0 && (
              <tr>
                <td className="cell-empty" colSpan={4} style={{ color: 'var(--txt-muted)', textAlign: 'center', padding: '2.5rem' }}>
                  {allTransfers.length === 0 ? (
                    <>
                      Belum ada transfer.
                      <div style={{ marginTop: '0.75rem' }}>
                        <button type="button" className="btn-chip" onClick={() => setIsPickerOpen(true)}>
                          <Plus size={14} />
                          Buat transfer pertama
                        </button>
                      </div>
                    </>
                  ) : (
                    'Tidak ada transfer yang cocok dengan filter saat ini.'
                  )}
                </td>
              </tr>
            )}
            {transfers.map((l) => (
              <tr key={l.id}>
                <td data-label="Waktu" style={{ color: 'var(--txt-muted)', whiteSpace: 'nowrap' }}>{l.timestamp}</td>
                <td data-label="Deskripsi" className="cell-lead" style={{ color: 'var(--txt-primary)' }}>{l.description}</td>
                <td data-label="Rute">
                  <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', flexWrap: 'wrap', justifyContent: 'flex-end' }}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.8rem', fontWeight: 700, color: SITE_COLOR[l.siteFrom] }}>
                      <span style={{ width: '7px', height: '7px', borderRadius: '50%', background: SITE_COLOR[l.siteFrom], flexShrink: 0 }} />
                      {SITE_LABEL[l.siteFrom]}
                    </span>
                    <ArrowRight size={13} color="#00D084" style={{ flexShrink: 0 }} />
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.8rem', fontWeight: 700, color: SITE_COLOR[l.siteTo] }}>
                      <span style={{ width: '7px', height: '7px', borderRadius: '50%', background: SITE_COLOR[l.siteTo], flexShrink: 0 }} />
                      {SITE_LABEL[l.siteTo]}
                    </span>
                  </span>
                </td>
                <td data-label="Oleh">
                  <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', color: 'var(--txt-tertiary)', justifyContent: 'flex-end', textAlign: 'right' }}>
                    <span style={{
                      width: '24px', height: '24px', borderRadius: '50%', background: 'rgba(0, 208, 132, 0.15)', color: '#00D084',
                      display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.65rem', fontWeight: 800, flexShrink: 0,
                    }}>
                      {initialsOf(l.performedBy)}
                    </span>
                    {l.performedBy}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <PartPickerModal
        isOpen={isPickerOpen}
        spareParts={spareParts}
        onClose={() => setIsPickerOpen(false)}
        onPick={(item) => {
          setIsPickerOpen(false);
          setTransferItem(item);
        }}
      />
      <TransferModal
        isOpen={!!transferItem}
        item={transferItem}
        onClose={() => setTransferItem(null)}
        onConfirmTransfer={(item, quantity, targetSite) => {
          onConfirmTransfer(item, quantity, targetSite);
          setTransferItem(null);
        }}
      />
    </div>
  );
};

/* ────────────────────────────── Maintenance ────────────────────────────── */
const STATUS_META: Record<'Critical' | 'Low Stock' | 'Maintenance Needed', { color: string; bg: string; icon: React.ElementType; rank: number }> = {
  Critical: { color: '#F87171', bg: 'rgba(248,113,113,0.12)', icon: AlertOctagon, rank: 0 },
  'Low Stock': { color: '#F59E0B', bg: 'rgba(245,158,11,0.12)', icon: AlertTriangle, rank: 1 },
  'Maintenance Needed': { color: '#A78BFA', bg: 'rgba(167,139,250,0.12)', icon: Wrench, rank: 2 },
};

/** Search + pick any spare part, add an optional note, then flag it for maintenance. */
const FlagMaintenanceModal: React.FC<{
  isOpen: boolean;
  spareParts: SparePart[];
  onClose: () => void;
  onSubmit: (item: SparePart, note: string) => void;
}> = ({ isOpen, spareParts, onClose, onSubmit }) => {
  const [q, setQ] = useState('');
  const [selected, setSelected] = useState<SparePart | null>(null);
  const [note, setNote] = useState('');

  if (!isOpen) return null;

  const query = q.trim().toLowerCase();
  const results = spareParts
    .filter((p) => p.status !== 'Maintenance Needed')
    .filter(
      (p) =>
        !query ||
        p.name.toLowerCase().includes(query) ||
        p.sku.toLowerCase().includes(query) ||
        SITE_LABEL[p.site].toLowerCase().includes(query)
    )
    .slice(0, 40);

  const handleClose = () => {
    setSelected(null);
    setQ('');
    setNote('');
    onClose();
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selected) return;
    onSubmit(selected, note.trim());
    handleClose();
  };

  return (
    <div className="admin-modal-overlay" style={{ zIndex: 110 }} onClick={(e) => { if (e.target === e.currentTarget) handleClose(); }}>
      <div className="glass-panel admin-modal-panel" style={{ maxWidth: '520px', border: '1px solid rgba(167,139,250,0.4)' }}>
        <button
          onClick={handleClose}
          style={{
            position: 'absolute', top: '1.25rem', right: '1.25rem',
            background: 'rgba(255, 255, 255, 0.05)', border: 'none', color: 'var(--txt-tertiary)',
            borderRadius: '50%', width: '32px', height: '32px', cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}
        >
          <X size={18} />
        </button>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.25rem', paddingRight: '2.75rem' }}>
          <div style={{ width: '44px', height: '44px', borderRadius: '12px', background: 'rgba(167,139,250,0.15)', color: '#A78BFA', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
            <Wrench size={22} />
          </div>
          <div style={{ minWidth: 0 }}>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: 'var(--txt-primary)' }}>Tandai untuk Maintenance</h3>
            <div style={{ fontSize: '0.8rem', color: 'var(--txt-muted)' }}>Pilih spare part yang butuh servis atau perhatian</div>
          </div>
        </div>

        {!selected ? (
          <>
            <div style={{ position: 'relative', marginBottom: '1rem' }}>
              <Search size={16} color="#64748B" style={{ position: 'absolute', left: '0.85rem', top: '50%', transform: 'translateY(-50%)' }} />
              <input
                autoFocus
                type="text"
                value={q}
                onChange={(e) => setQ(e.target.value)}
                placeholder="Cari nama, SKU, atau site..."
                style={{ ...emptyInputStyle, width: '100%', padding: '0.7rem 0.85rem 0.7rem 2.5rem' }}
              />
            </div>
            <div style={{ maxHeight: '340px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              {results.length === 0 && (
                <div style={{ color: 'var(--txt-muted)', fontSize: '0.85rem', textAlign: 'center', padding: '1.5rem 0' }}>
                  Tidak ada spare part yang cocok.
                </div>
              )}
              {results.map((p) => {
                const visual = getCategoryVisual(p.category);
                const Icon = visual.icon || Package;
                return (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => setSelected(p)}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '0.75rem',
                      background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)',
                      borderRadius: '10px', padding: '0.6rem 0.75rem', cursor: 'pointer', textAlign: 'left',
                    }}
                    onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'rgba(167,139,250,0.4)'; e.currentTarget.style.background = 'rgba(167,139,250,0.06)'; }}
                    onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'rgba(255,255,255,0.07)'; e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; }}
                  >
                    {p.imageUrl ? (
                      <img src={p.imageUrl} alt={p.name} style={{ width: '38px', height: '38px', borderRadius: '8px', objectFit: 'cover', flexShrink: 0, border: '1px solid rgba(255,255,255,0.1)' }} />
                    ) : (
                      <div style={{ width: '38px', height: '38px', borderRadius: '8px', background: visual.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                        <Icon size={18} color={visual.color} />
                      </div>
                    )}
                    <div style={{ minWidth: 0, flex: 1 }}>
                      <div style={{ fontSize: '0.75rem', color: '#00D084', fontFamily: 'monospace', fontWeight: 700 }}>{p.sku}</div>
                      <div style={{ fontSize: '0.9rem', color: 'var(--txt-primary)', fontWeight: 600, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{p.name}</div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--txt-muted)', marginTop: '0.1rem' }}>Site {SITE_LABEL[p.site]} &middot; {p.stock} {p.unit}</div>
                    </div>
                    <ArrowRight size={16} color="#64748B" style={{ flexShrink: 0 }} />
                  </button>
                );
              })}
            </div>
          </>
        ) : (
          <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.1rem' }}>
            <div style={{ background: 'rgba(10, 15, 29, 0.8)', border: '1px solid rgba(255, 255, 255, 0.08)', borderRadius: '12px', padding: '1rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
              {selected.imageUrl ? (
                <img src={selected.imageUrl} alt={selected.name} style={{ width: '48px', height: '48px', borderRadius: '10px', objectFit: 'cover', flexShrink: 0, border: '1px solid rgba(255,255,255,0.1)' }} />
              ) : (
                <div style={{ width: '48px', height: '48px', borderRadius: '10px', background: 'rgba(167,139,250,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  <Wrench size={22} color="#A78BFA" />
                </div>
              )}
              <div style={{ minWidth: 0 }}>
                <div style={{ fontSize: '0.75rem', color: '#00D084', fontFamily: 'monospace', fontWeight: 700 }}>{selected.sku}</div>
                <div style={{ fontSize: '0.95rem', fontWeight: 700, color: 'var(--txt-primary)' }}>{selected.name}</div>
                <div style={{ fontSize: '0.78rem', color: 'var(--txt-muted)' }}>Site {SITE_LABEL[selected.site]} &middot; Status saat ini: {selected.status}</div>
              </div>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--txt-tertiary)', marginBottom: '0.4rem', fontWeight: 600 }}>
                Catatan / Alasan (opsional)
              </label>
              <textarea
                value={note}
                onChange={(e) => setNote(e.target.value)}
                placeholder="Contoh: kebocoran seal terdeteksi saat inspeksi rutin..."
                rows={3}
                style={{ ...emptyInputStyle, width: '100%', resize: 'vertical', fontFamily: 'inherit' }}
              />
            </div>

            <div style={{ display: 'flex', gap: '0.75rem' }}>
              <button type="button" className="btn-chip" onClick={() => setSelected(null)} style={{ flex: 1, justifyContent: 'center' }}>
                Ganti Item
              </button>
              <button type="submit" className="btn-primary" style={{ flex: 2, justifyContent: 'center' }}>
                <Wrench size={16} />
                Tandai untuk Maintenance
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};

export const MaintenanceView: React.FC<{
  spareParts: SparePart[];
  onFlagMaintenance: (item: SparePart, note: string) => void;
  onResolveMaintenance: (item: SparePart) => void;
}> = ({ spareParts, onFlagMaintenance, onResolveMaintenance }) => {
  const [isFlagOpen, setIsFlagOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'Critical' | 'Low Stock' | 'Maintenance Needed'>('all');
  const [siteFilter, setSiteFilter] = useState<SiteLocation | 'all'>('all');

  const allItems = useMemo(
    () => spareParts.filter((p) => p.status === 'Maintenance Needed' || p.status === 'Critical' || p.status === 'Low Stock'),
    [spareParts]
  );

  const filtersActive = search.trim() !== '' || statusFilter !== 'all' || siteFilter !== 'all';

  const items = useMemo(() => {
    const q = search.trim().toLowerCase();
    const list = allItems.filter((p) => {
      if (statusFilter !== 'all' && p.status !== statusFilter) return false;
      if (siteFilter !== 'all' && p.site !== siteFilter) return false;
      if (q && !p.name.toLowerCase().includes(q) && !p.sku.toLowerCase().includes(q)) return false;
      return true;
    });
    return [...list].sort((a, b) => {
      const rankDiff = STATUS_META[a.status as keyof typeof STATUS_META].rank - STATUS_META[b.status as keyof typeof STATUS_META].rank;
      if (rankDiff !== 0) return rankDiff;
      return a.lastInspected.localeCompare(b.lastInspected); // oldest inspection first within same severity
    });
  }, [allItems, search, statusFilter, siteFilter]);

  const criticalCount = allItems.filter((p) => p.status === 'Critical').length;
  const lowStockCount = allItems.filter((p) => p.status === 'Low Stock').length;
  const maintenanceCount = allItems.filter((p) => p.status === 'Maintenance Needed').length;
  const restockCost = allItems.reduce((sum, p) => sum + Math.max(0, p.minStock - p.stock) * p.priceEstimate, 0);

  const statCards = [
    { label: 'Butuh Perhatian', value: allItems.length.toLocaleString('id-ID'), icon: ClipboardCheck, color: '#00D084' },
    { label: 'Critical', value: criticalCount.toLocaleString('id-ID'), icon: AlertOctagon, color: '#F87171' },
    { label: 'Low Stock', value: lowStockCount.toLocaleString('id-ID'), icon: AlertTriangle, color: '#F59E0B' },
    { label: 'Maintenance Needed', value: maintenanceCount.toLocaleString('id-ID'), icon: Wrench, color: '#A78BFA' },
    { label: 'Estimasi Biaya Restock', value: formatIDR(restockCost), icon: Wallet, color: '#60A5FA' },
  ];

  const resetFilters = () => {
    setSearch('');
    setStatusFilter('all');
    setSiteFilter('all');
  };

  const siteOptions: SiteLocation[] = ['bekasi', 'indramayu', 'blora', 'setu'];

  return (
    <div>
      <div className="view-toolbar-row" style={{ display: 'flex', flexWrap: 'wrap', gap: '1rem', justifyContent: 'space-between', alignItems: 'flex-end' }}>
        <PageHeader icon={Wrench} title="Maintenance" sub="Spare part yang butuh servis, pengadaan, atau perhatian segera" />
        <button type="button" className="btn-primary view-toolbar-btn" onClick={() => setIsFlagOpen(true)} style={{ marginBottom: '1.5rem' }}>
          <Plus size={18} />
          Tandai untuk Maintenance
        </button>
      </div>

      {/* Summary cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '1rem', marginBottom: '1.5rem' }}>
        {statCards.map((s) => (
          <div key={s.label} className="glass-panel" style={{ borderRadius: '16px', padding: '1.25rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
              <div style={{ width: '38px', height: '38px', borderRadius: '10px', background: `${s.color}26`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <s.icon size={18} color={s.color} />
              </div>
              <div style={{ fontSize: '0.75rem', color: 'var(--txt-tertiary)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.02em' }}>{s.label}</div>
            </div>
            <div style={{ fontSize: '1.25rem', fontWeight: 800, color: 'var(--txt-primary)', lineHeight: 1.2 }}>{s.value}</div>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="glass-panel" style={{ borderRadius: '16px', padding: '1rem 1.25rem', marginBottom: '1.5rem', display: 'flex', flexWrap: 'wrap', gap: '0.75rem', alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--txt-muted)', fontSize: '0.8rem', fontWeight: 700 }}>
          <Filter size={15} />
          Filter
        </div>
        <div style={{ position: 'relative', flex: '1 1 220px', minWidth: '180px' }}>
          <Search size={15} color="#64748B" style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)' }} />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Cari nama atau SKU..."
            style={{ ...emptyInputStyle, width: '100%', padding: '0.65rem 0.85rem 0.65rem 2.25rem' }}
          />
        </div>
        <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as typeof statusFilter)} style={{ ...emptyInputStyle, cursor: 'pointer' }}>
          <option value="all">Semua Status</option>
          <option value="Critical">Critical</option>
          <option value="Low Stock">Low Stock</option>
          <option value="Maintenance Needed">Maintenance Needed</option>
        </select>
        <select value={siteFilter} onChange={(e) => setSiteFilter(e.target.value as SiteLocation | 'all')} style={{ ...emptyInputStyle, cursor: 'pointer' }}>
          <option value="all">Semua Site</option>
          {siteOptions.map((s) => <option key={s} value={s}>Site {SITE_LABEL[s]}</option>)}
        </select>
        {filtersActive && (
          <button type="button" className="btn-chip" onClick={resetFilters}>
            <RotateCcw size={14} />
            Reset
          </button>
        )}
      </div>

      <div style={{ fontSize: '0.8rem', color: 'var(--txt-muted)', fontWeight: 700, marginBottom: '0.75rem', textTransform: 'uppercase' }}>
        Daftar Item ({items.length})
      </div>

      <div className="glass-panel simple-table-wrap" style={{ borderRadius: '16px', padding: '0.5rem' }}>
        <table className="simple-table">
          <thead>
            <tr>
              <th>Spare Part</th>
              <th>Site</th>
              <th>Status</th>
              <th>Stok / Min</th>
              <th>Terakhir Diperiksa</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {items.length === 0 && (
              <tr>
                <td className="cell-empty" colSpan={6} style={{ color: 'var(--txt-muted)', textAlign: 'center', padding: '2.5rem' }}>
                  {allItems.length === 0 ? 'Tidak ada item yang butuh perhatian. 🎉' : 'Tidak ada item yang cocok dengan filter saat ini.'}
                </td>
              </tr>
            )}
            {items.map((p) => {
              const meta = STATUS_META[p.status as keyof typeof STATUS_META];
              const StatusIcon = meta.icon;
              const visual = getCategoryVisual(p.category);
              const CategoryIcon = visual.icon || Package;
              return (
                <tr key={p.id}>
                  <td className="cell-lead">
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                      {p.imageUrl ? (
                        <img src={p.imageUrl} alt={p.name} className="spare-thumb-photo" loading="lazy" style={{ width: '44px', height: '44px', borderRadius: '10px' }} />
                      ) : (
                        <div className="spare-thumb-icon" style={{ width: '44px', height: '44px', borderRadius: '10px', background: visual.bg, border: `1px solid ${visual.color}33` }}>
                          <CategoryIcon size={18} color={visual.color} strokeWidth={1.75} />
                        </div>
                      )}
                      <div style={{ minWidth: 0 }}>
                        <div style={{ fontFamily: 'monospace', color: '#00D084', fontSize: '0.75rem', fontWeight: 700 }}>{p.sku}</div>
                        <div style={{ color: 'var(--txt-primary)', fontWeight: 600 }}>{p.name}</div>
                      </div>
                    </div>
                  </td>
                  <td data-label="Site">Site {SITE_LABEL[p.site]}</td>
                  <td data-label="Status">
                    <span
                      style={{
                        display: 'inline-flex', alignItems: 'center', gap: '0.35rem',
                        fontSize: '0.75rem', fontWeight: 700, padding: '0.25rem 0.65rem', borderRadius: '999px',
                        color: meta.color, background: meta.bg,
                      }}
                    >
                      <StatusIcon size={12} />
                      {p.status}
                    </span>
                  </td>
                  <td data-label="Stok / Min" style={{ color: p.stock <= p.minStock ? meta.color : 'var(--txt-secondary)', fontWeight: 700 }}>{p.stock} / {p.minStock}</td>
                  <td data-label="Terakhir Diperiksa" style={{ color: 'var(--txt-tertiary)' }}>{p.lastInspected}</td>
                  <td className="cell-action" style={{ textAlign: 'right' }}>
                    <button
                      type="button"
                      className="btn-chip"
                      onClick={() => onResolveMaintenance(p)}
                      style={{ padding: '0.45rem 0.8rem', fontSize: '0.75rem' }}
                    >
                      <CheckCircle2 size={13} />
                      Tandai Selesai
                    </button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <FlagMaintenanceModal
        isOpen={isFlagOpen}
        spareParts={spareParts}
        onClose={() => setIsFlagOpen(false)}
        onSubmit={onFlagMaintenance}
      />
    </div>
  );
};

/* ────────────────────────────── Audit / Log ────────────────────────────── */
export const ACTION_META: Record<ActivityLog['action'], { label: string; color: string; bg: string; icon: React.ElementType }> = {
  TRANSFER: { label: 'Transfer Antar Site', color: '#00D084', bg: 'rgba(0, 208, 132, 0.12)', icon: ArrowLeftRight },
  STOCK_UPDATE: { label: 'Update Stok', color: '#60A5FA', bg: 'rgba(96, 165, 250, 0.12)', icon: RefreshCw },
  ADD_SPARE_PART: { label: 'Item Baru', color: '#34D399', bg: 'rgba(52, 211, 153, 0.12)', icon: PlusCircle },
  DELETE_SPARE_PART: { label: 'Item Dihapus', color: '#F87171', bg: 'rgba(248, 113, 113, 0.12)', icon: Trash2 },
};

/** Parses the app's canonical "YYYY-MM-DD HH:mm" log timestamp. Falls back
 * to native Date parsing for any legacy/odd formats so nothing crashes. */
export function parseLogDate(ts: string): Date | null {
  const iso = ts.match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})/);
  if (iso) {
    const [, y, mo, d, h, mi] = iso;
    return new Date(Number(y), Number(mo) - 1, Number(d), Number(h), Number(mi));
  }
  const fallback = new Date(ts);
  return Number.isNaN(fallback.getTime()) ? null : fallback;
}

export function timeAgo(ts: string): string {
  const date = parseLogDate(ts);
  if (!date) return ts;
  const diffMs = Date.now() - date.getTime();
  const minutes = Math.floor(diffMs / 60000);
  if (minutes < 1) return 'Baru saja';
  if (minutes < 60) return `${minutes} menit lalu`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours} jam lalu`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days} hari lalu`;
  return date.toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' });
}

export const AuditView: React.FC<{ logs: ActivityLog[] }> = ({ logs }) => {
  const [search, setSearch] = useState('');
  const [actionFilter, setActionFilter] = useState<'all' | ActivityLog['action']>('all');
  const [sortOrder, setSortOrder] = useState<'newest' | 'oldest'>('newest');

  const sortedAll = useMemo(
    () =>
      [...logs].sort((a, b) => {
        const da = parseLogDate(a.timestamp)?.getTime() ?? 0;
        const db = parseLogDate(b.timestamp)?.getTime() ?? 0;
        return db - da;
      }),
    [logs]
  );

  const filtersActive = search.trim() !== '' || actionFilter !== 'all';

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    let list = sortedAll.filter((l) => {
      if (actionFilter !== 'all' && l.action !== actionFilter) return false;
      if (q && !l.description.toLowerCase().includes(q) && !l.performedBy.toLowerCase().includes(q)) return false;
      return true;
    });
    if (sortOrder === 'oldest') list = [...list].reverse();
    return list;
  }, [sortedAll, search, actionFilter, sortOrder]);

  const weekCount = useMemo(() => {
    const cutoff = Date.now() - 7 * 24 * 60 * 60 * 1000;
    return sortedAll.filter((l) => {
      const t = parseLogDate(l.timestamp)?.getTime();
      return t !== undefined && t !== null && t >= cutoff;
    }).length;
  }, [sortedAll]);

  const countByAction = (action: ActivityLog['action']) => sortedAll.filter((l) => l.action === action).length;

  const statCards = [
    { label: 'Total Aktivitas', value: sortedAll.length, icon: History, color: '#00D084' },
    { label: '7 Hari Terakhir', value: weekCount, icon: CalendarClock, color: '#FBBF24' },
    { label: 'Transfer', value: countByAction('TRANSFER'), icon: ArrowLeftRight, color: '#00D084' },
    { label: 'Update Stok', value: countByAction('STOCK_UPDATE'), icon: RefreshCw, color: '#60A5FA' },
    { label: 'Perubahan Katalog', value: countByAction('ADD_SPARE_PART') + countByAction('DELETE_SPARE_PART'), icon: ClipboardList, color: '#C084FC' },
  ];

  const resetFilters = () => {
    setSearch('');
    setActionFilter('all');
  };

  const handleExportCsv = () => {
    const header = ['Waktu', 'Aksi', 'Deskripsi', 'Oleh'];
    const rows = filtered.map((l) => [l.timestamp, ACTION_META[l.action].label, l.description.replace(/"/g, "'"), l.performedBy.replace(/"/g, "'")]);
    const csv = [header, ...rows].map((r) => r.map((cell) => `"${cell}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `reethau-audit-log-${new Date().toISOString().slice(0, 10)}.csv`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const actionChips: Array<{ key: 'all' | ActivityLog['action']; label: string }> = [
    { key: 'all', label: 'Semua' },
    { key: 'TRANSFER', label: ACTION_META.TRANSFER.label },
    { key: 'STOCK_UPDATE', label: ACTION_META.STOCK_UPDATE.label },
    { key: 'ADD_SPARE_PART', label: ACTION_META.ADD_SPARE_PART.label },
    { key: 'DELETE_SPARE_PART', label: ACTION_META.DELETE_SPARE_PART.label },
  ];

  return (
    <div>
      <div className="view-toolbar-row" style={{ display: 'flex', flexWrap: 'wrap', gap: '1rem', justifyContent: 'space-between', alignItems: 'flex-end' }}>
        <PageHeader icon={ClipboardList} title="Audit / Log Aktivitas" sub="Seluruh riwayat perubahan data inventaris, tercatat otomatis dan tidak dapat diubah" />
        <button
          type="button"
          className="btn-chip view-toolbar-btn"
          onClick={handleExportCsv}
          disabled={filtered.length === 0}
          style={filtered.length === 0 ? { opacity: 0.5, cursor: 'not-allowed', justifyContent: 'center' } : { justifyContent: 'center' }}
        >
          <Download size={15} />
          Ekspor CSV
        </button>
      </div>

      {/* Summary cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '1rem', marginBottom: '1.5rem' }}>
        {statCards.map((s) => (
          <div key={s.label} className="glass-panel" style={{ borderRadius: '16px', padding: '1.1rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem', marginBottom: '0.65rem' }}>
              <div style={{ width: '34px', height: '34px', borderRadius: '9px', background: `${s.color}26`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <s.icon size={16} color={s.color} />
              </div>
              <div style={{ fontSize: '0.72rem', color: 'var(--txt-tertiary)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.02em' }}>{s.label}</div>
            </div>
            <div style={{ fontSize: '1.3rem', fontWeight: 800, color: 'var(--txt-primary)', lineHeight: 1.2 }}>{s.value.toLocaleString('id-ID')}</div>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="glass-panel" style={{ borderRadius: '16px', padding: '1rem 1.25rem', marginBottom: '1.5rem', display: 'flex', flexWrap: 'wrap', gap: '0.75rem', alignItems: 'center' }}>
        <div style={{ position: 'relative', flex: '1 1 220px', minWidth: '180px' }}>
          <Search size={15} color="#64748B" style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)' }} />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Cari deskripsi atau nama petugas..."
            style={{ ...emptyInputStyle, width: '100%', padding: '0.65rem 0.85rem 0.65rem 2.25rem' }}
          />
        </div>
        <select value={sortOrder} onChange={(e) => setSortOrder(e.target.value as 'newest' | 'oldest')} style={{ ...emptyInputStyle, cursor: 'pointer', flex: '1 1 150px' }}>
          <option value="newest">Terbaru dahulu</option>
          <option value="oldest">Terlama dahulu</option>
        </select>
        {filtersActive && (
          <button type="button" className="btn-chip" onClick={resetFilters}>
            <RotateCcw size={14} />
            Reset
          </button>
        )}
      </div>

      {/* Action type chips */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '1.5rem' }}>
        {actionChips.map((chip) => {
          const isActive = actionFilter === chip.key;
          const meta = chip.key === 'all' ? null : ACTION_META[chip.key];
          return (
            <button
              key={chip.key}
              type="button"
              onClick={() => setActionFilter(chip.key)}
              style={{
                display: 'inline-flex', alignItems: 'center', gap: '0.4rem',
                fontSize: '0.78rem', fontWeight: 700, padding: '0.45rem 0.9rem', borderRadius: '999px',
                cursor: 'pointer', transition: 'all 0.15s ease',
                color: isActive ? 'var(--txt-inverse)' : meta ? meta.color : 'var(--txt-secondary)',
                background: isActive ? (meta ? meta.color : '#00D084') : meta ? meta.bg : 'rgba(255,255,255,0.06)',
                border: `1px solid ${isActive ? 'transparent' : meta ? `${meta.color}44` : 'rgba(255,255,255,0.12)'}`,
              }}
            >
              {meta && <meta.icon size={13} />}
              {chip.label}
              <span style={{ opacity: 0.75, fontWeight: 800 }}>
                {chip.key === 'all' ? sortedAll.length : countByAction(chip.key)}
              </span>
            </button>
          );
        })}
      </div>

      {/* Timeline */}
      {filtered.length === 0 ? (
        <div className="glass-panel" style={{ borderRadius: '16px', padding: '3rem 1.5rem', textAlign: 'center', color: 'var(--txt-muted)' }}>
          {sortedAll.length === 0 ? 'Belum ada log aktivitas.' : 'Tidak ada log yang cocok dengan filter saat ini.'}
        </div>
      ) : (
        <div className="glass-panel audit-timeline" style={{ borderRadius: '16px', padding: '1.5rem' }}>
          {filtered.map((l, i) => {
            const meta = ACTION_META[l.action];
            const Icon = meta.icon;
            return (
              <div key={l.id} className="audit-timeline-item">
                <div className="audit-timeline-rail">
                  <div className="audit-timeline-dot" style={{ background: meta.bg, border: `2px solid ${meta.color}` }}>
                    <Icon size={15} color={meta.color} />
                  </div>
                  {i < filtered.length - 1 && <div className="audit-timeline-line" />}
                </div>
                <div className="audit-timeline-content">
                  <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '0.5rem', marginBottom: '0.4rem' }}>
                    <span
                      style={{
                        fontSize: '0.7rem', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.03em',
                        color: meta.color, background: meta.bg, padding: '0.2rem 0.55rem', borderRadius: '999px',
                      }}
                    >
                      {meta.label}
                    </span>
                    <span style={{ fontSize: '0.75rem', color: 'var(--txt-muted)', display: 'inline-flex', alignItems: 'center', gap: '0.3rem' }}>
                      <Clock size={11} />
                      {timeAgo(l.timestamp)} &middot; {l.timestamp}
                    </span>
                  </div>
                  <div style={{ color: 'var(--txt-primary)', fontSize: '0.92rem', lineHeight: 1.5, marginBottom: '0.5rem' }}>{l.description}</div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--txt-tertiary)', fontSize: '0.8rem' }}>
                    <span style={{
                      width: '22px', height: '22px', borderRadius: '50%', background: 'rgba(255,255,255,0.06)', color: 'var(--txt-secondary)',
                      display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.62rem', fontWeight: 800, flexShrink: 0,
                    }}>
                      {initialsOf(l.performedBy)}
                    </span>
                    {l.performedBy}
                    {l.siteFrom && (
                      <>
                        <span style={{ color: 'var(--txt-muted)' }}>&bull;</span>
                        <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.3rem' }}>
                          <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: SITE_COLOR[l.siteFrom] }} />
                          Site {SITE_LABEL[l.siteFrom]}
                          {l.siteTo && (
                            <>
                              <ArrowRight size={11} color="#64748B" />
                              <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: SITE_COLOR[l.siteTo] }} />
                              Site {SITE_LABEL[l.siteTo]}
                            </>
                          )}
                        </span>
                      </>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

/* ────────────────────────────── Branches (Sites) ────────────────────────────── */
export const BranchesView: React.FC<{ spareParts: SparePart[] }> = ({ spareParts }) => {
  const sites: SiteLocation[] = ['bekasi', 'indramayu', 'blora', 'setu'];
  const [qrSite, setQrSite] = useState<SiteLocation | null>(null);

  return (
    <div>
      <PageHeader icon={MapPin} title="Site Operasional" sub="Ringkasan inventaris di tiap lokasi Reethau — ketuk ikon QR untuk kode akses cepat site" />
      <div className="site-grid" style={{ marginBottom: '1rem' }}>
        {sites.map((site) => {
          const items = spareParts.filter((p) => p.site === site);
          const value = items.reduce((acc, p) => acc + p.stock * p.priceEstimate, 0);
          const lowStock = items.filter((p) => p.stock <= p.minStock).length;
          return (
            <div key={site} className="site-card active" style={{ minHeight: '160px', cursor: 'default' }}>
              <div className="site-card-bg" style={{ backgroundImage: `url(${SITE_IMAGE[site]})` }} />
              <div className="site-card-overlay" />
              <button
                className="site-card-qr-btn"
                title={`QR Code Site ${SITE_LABEL[site]}`}
                aria-label={`Tampilkan QR Code Site ${SITE_LABEL[site]}`}
                onClick={(e) => { e.stopPropagation(); setQrSite(site); }}
              >
                <QrCodeIcon size={16} />
              </button>
              <div className="site-card-content" style={{ flexDirection: 'column', alignItems: 'flex-start', gap: '0.5rem' }}>
                <div>
                  <div className="site-card-label"><MapPin size={16} />Site {SITE_LABEL[site]}</div>
                  <div className="site-card-sub">{SITE_SUB[site]}</div>
                </div>
                <div style={{ display: 'flex', gap: '1rem', fontSize: '0.75rem', color: 'var(--txt-primary)' }}>
                  <span>{items.length} jenis part</span>
                  <span>{lowStock} stok kritis</span>
                </div>
                <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#00D084' }}>{formatIDR(value)}</div>
              </div>
            </div>
          );
        })}
      </div>

      {qrSite && (
        <QRCodeModal
          isOpen={!!qrSite}
          onClose={() => setQrSite(null)}
          title={`Site ${SITE_LABEL[qrSite]}`}
          subtitle={`REETHAU-SITE-${qrSite.toUpperCase()}`}
          value={`https://inventory.reethau.id/site/${qrSite}`}
          fileName={`reethau-site-${qrSite}-qr`}
          metaLines={[
            { label: 'Deskripsi', value: SITE_SUB[qrSite] },
            { label: 'Jenis Part', value: `${spareParts.filter((p) => p.site === qrSite).length} terdaftar` },
          ]}
        />
      )}
    </div>
  );
};

/* ────────────────────────────── Asset Photo Gallery (Site Setu) ────────────────────────────── */
export const GalleryView: React.FC = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  const close = () => setActiveIndex(null);
  const showPrev = () =>
    setActiveIndex((i) => (i === null ? null : (i - 1 + SETU_GALLERY.length) % SETU_GALLERY.length));
  const showNext = () =>
    setActiveIndex((i) => (i === null ? null : (i + 1) % SETU_GALLERY.length));

  return (
    <div>
      <PageHeader
        icon={Images}
        title="Galeri Aset — Site Setu"
        sub={`${SETU_GALLERY.length} dokumentasi foto peralatan & instalasi lapangan Site Setu (Compressor Station & Fleet Room)`}
      />
      <div className="gallery-grid">
        {SETU_GALLERY.map((photo, idx) => (
          <button key={photo.src} className="gallery-card" onClick={() => setActiveIndex(idx)}>
            <img src={photo.src} alt={photo.caption} loading="lazy" />
            <div className="gallery-card-caption">{photo.caption}</div>
          </button>
        ))}
      </div>

      {activeIndex !== null && (
        <div
          className="gallery-lightbox"
          onClick={(e) => { if (e.target === e.currentTarget) close(); }}
          role="dialog"
          aria-modal="true"
        >
          <button className="gallery-lightbox-close" onClick={close} aria-label="Tutup galeri">
            <X size={20} />
          </button>
          <button className="gallery-lightbox-nav prev" onClick={showPrev} aria-label="Foto sebelumnya">
            <ChevronLeft size={22} />
          </button>
          <img
            src={SETU_GALLERY[activeIndex].src}
            alt={SETU_GALLERY[activeIndex].caption}
            className="gallery-lightbox-img"
          />
          <button className="gallery-lightbox-nav next" onClick={showNext} aria-label="Foto berikutnya">
            <ChevronRight size={22} />
          </button>
          <div className="gallery-lightbox-caption">
            {SETU_GALLERY[activeIndex].caption} — ({activeIndex + 1}/{SETU_GALLERY.length})
          </div>
        </div>
      )}
    </div>
  );
};

/* ────────────────────────────── Product Lines ────────────────────────────── */
export const ProductLinesView: React.FC<{ spareParts: SparePart[] }> = ({ spareParts }) => {
  const lines = ['CNG', 'LNG', 'Biomass'] as const;
  const colors: Record<string, string> = { CNG: '#38BDF8', LNG: '#F472B6', Biomass: '#A3E635' };
  return (
    <div>
      <PageHeader icon={Layers} title="Lini Produk Energi" sub="Spare part dikelompokkan berdasarkan lini produk clean energy Reethau" />
      <div className="kpi-grid">
        {lines.map((line) => {
          const items = spareParts.filter((p) => p.productEnergy === line);
          const stock = items.reduce((acc, p) => acc + p.stock, 0);
          const value = items.reduce((acc, p) => acc + p.stock * p.priceEstimate, 0);
          return (
            <div key={line} className="glass-panel" style={{ borderRadius: '16px', padding: '1.25rem', borderTop: `3px solid ${colors[line]}` }}>
              <div style={{ fontSize: '0.85rem', color: 'var(--txt-tertiary)', fontWeight: 700 }}>{line} Line</div>
              <div style={{ fontSize: '1.8rem', fontWeight: 800, color: 'var(--txt-primary)', marginTop: '0.5rem' }}>
                {stock} <span style={{ fontSize: '0.8rem', color: 'var(--txt-muted)', fontWeight: 500 }}>unit / {items.length} jenis</span>
              </div>
              <div style={{ fontSize: '0.8rem', color: colors[line], marginTop: '0.4rem', fontWeight: 700 }}>{formatIDR(value)}</div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

/* ────────────────────────────── Team (from log activity) ────────────────────────────── */
export const TeamView: React.FC<{ logs: ActivityLog[] }> = ({ logs }) => {
  const roster = Object.entries(
    logs.reduce<Record<string, number>>((acc, l) => {
      acc[l.performedBy] = (acc[l.performedBy] || 0) + 1;
      return acc;
    }, {})
  ).sort((a, b) => b[1] - a[1]);

  const initials = (name: string) =>
    name
      .split(' ')
      .slice(0, 2)
      .map((w) => w[0])
      .join('')
      .toUpperCase();

  return (
    <div>
      <PageHeader icon={Users} title="Tim Lapangan" sub="Personel yang tercatat aktif melakukan perubahan data inventaris" />
      <div className="roster-grid">
        {roster.length === 0 && (
          <div style={{ color: 'var(--txt-muted)' }}>Belum ada aktivitas tercatat.</div>
        )}
        {roster.map(([name, count]) => (
          <div key={name} className="glass-panel roster-card">
            <div className="roster-avatar">{initials(name)}</div>
            <div style={{ minWidth: 0 }}>
              <div style={{ color: 'var(--txt-primary)', fontWeight: 700, fontSize: '0.88rem' }}>{name}</div>
              <div style={{ color: 'var(--txt-muted)', fontSize: '0.75rem', marginTop: '0.15rem' }}>{count} aktivitas tercatat</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};